# Golang CircleCI 2.0 conf file

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1

    working_directory: /go/src/github.com/gnosthi/primecalc
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make test
